// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlftorJ80Gw3u4oK9vB_pg_-tEUscLqQQ',
    appId: '1:70950904094:web:6fedbf06346fdea45da90f',
    messagingSenderId: '70950904094',
    projectId: 'weather-app-flutter-8c417',
    authDomain: 'weather-app-flutter-8c417.firebaseapp.com',
    storageBucket: 'weather-app-flutter-8c417.appspot.com',
    measurementId: 'G-J3JEPMFXWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU5SqE3q1y3i27RDqlEHoTtnI5VOpe-6k',
    appId: '1:70950904094:android:9f98d4a415c2a6615da90f',
    messagingSenderId: '70950904094',
    projectId: 'weather-app-flutter-8c417',
    storageBucket: 'weather-app-flutter-8c417.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs0xs6s9oJOR5z61BXnzqM8x_WDMj5ps4',
    appId: '1:70950904094:ios:a4b4ddd556685af15da90f',
    messagingSenderId: '70950904094',
    projectId: 'weather-app-flutter-8c417',
    storageBucket: 'weather-app-flutter-8c417.appspot.com',
    iosClientId: '70950904094-ajnpm47p2v7rop5etsai8rj29mht6jak.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs0xs6s9oJOR5z61BXnzqM8x_WDMj5ps4',
    appId: '1:70950904094:ios:a4b4ddd556685af15da90f',
    messagingSenderId: '70950904094',
    projectId: 'weather-app-flutter-8c417',
    storageBucket: 'weather-app-flutter-8c417.appspot.com',
    iosClientId: '70950904094-ajnpm47p2v7rop5etsai8rj29mht6jak.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlftorJ80Gw3u4oK9vB_pg_-tEUscLqQQ',
    appId: '1:70950904094:web:96c7f0a58a14fff65da90f',
    messagingSenderId: '70950904094',
    projectId: 'weather-app-flutter-8c417',
    authDomain: 'weather-app-flutter-8c417.firebaseapp.com',
    storageBucket: 'weather-app-flutter-8c417.appspot.com',
    measurementId: 'G-C2QGBRTWTX',
  );

}